# Generated by Django 4.1.4 on 2022-12-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteEcomm', '0004_landingpage_image_alter_landingpage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alltemplates',
            name='image',
        ),
    ]
