# Generated by Django 4.1.4 on 2022-12-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteEcomm', '0005_remove_alltemplates_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltemplates',
            name='category',
            field=models.CharField(choices=[('landing-page', 'landing-page')], default='landing-page', max_length=200),
        ),
        migrations.AddField(
            model_name='alltemplates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
